### ISSUE TITLE
Uncaught Error: EPERM, operation not permitted 'C:\Users\Isaac\Documents\AtomProjects\Perp\a.exe'

### ISSUE THREAD

**Issue by Izacht13** [olmokramer/atom-permanent-delete#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Microsoft Windows 8.1
**Thrown From**: [permanent-delete](https://github.com/olmokramer/atom-permanent-delete) package, v0.1.2
### Stack Trace

Uncaught Error: EPERM, operation not permitted 'C:\Users\Isaac\Documents\AtomProjects\Perp\a.exe'

```
At fs.js:900

Error: EPERM, operation not permitted 'C:\Users\Isaac\Documents\AtomProjects\Perp\a.exe'
  at Error (native)
  at Object.fs.unlinkSync (fs.js:900:18)
  at C:\Users\Isaac\.atom\packages\permanent-delete\lib\permanent-delete.coffee:47:19
  at C:\Users\Isaac\AppData\Local\atom\app-0.187.0\resources\app\node_modules\fs-plus\lib\fs-plus.js:112:22
  at FSReqWrap.oncomplete (fs.js:100:15)

```
### Commands

```
     -1:25.6 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
     -1:22.3 command-palette:toggle (atom-text-editor.editor)
     -1:21.1 core:confirm (atom-text-editor.editor.mini)
     -1:21.1 settings-view:open (atom-text-editor.editor)
     -0:42.6 permanent-delete:delete (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "projectHome": "C:\\Users\\Isaac\\Documents\\AtomProjects",
    "disabledPackages": [
      "wrap-guide"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-clang, v0.6.2
autocomplete-css, v0.4.0
autocomplete-glsl, v0.1.4
autocomplete-haxe, v0.2.0
autocomplete-html, v0.3.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.2
color-picker, v1.4.4
language-glsl, v1.0.1
language-haxe, v0.2.1
language-rust, v0.4.2
linter, v0.12.0
linter-rust, v0.0.5
permanent-delete, v0.1.2
racer, v0.9.1
seti-syntax, v0.3.3
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by olmokramer** [comment]
Do you have permissions to delete the `.exe`? Or was the `.exe` maybe still running?

**Comment by Izacht13** [comment]
Im not sure, i'm having a lot of strange issues with MinGW, I can't even compile a simple "Hello World" program.

Minaswell` discard this issue, sorry for posting it.

**Comment by olmokramer** [comment]
Yeah, this package just uses node's `fs.unlink` to delete the files from the hard drive, so I think there's not a lot I can do about this. I'll close this issue now. Good luck sorting out your problems.
