### ISSUE TITLE
Uncaught TypeError: treeView.mainModule.createView is not a function

### ISSUE THREAD

**Issue by pr22m** [olmokramer/atom-permanent-delete#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [permanent-delete](https://github.com/olmokramer/atom-permanent-delete) package 0.1.5

### Stack Trace

Uncaught TypeError: treeView.mainModule.createView is not a function

```
At C:\Users\Pr\.atom\packages\permanent-delete\lib\permanent-delete.js:26

TypeError: treeView.mainModule.createView is not a function
    at /packages/permanent-delete/lib/permanent-delete.js:26:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:265:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:23.1.0 permanent-delete:delete (div.tool-panel.tree-view)
```

### Non-Core Packages

```
permanent-delete 0.1.5 
```

**Comment by Dayjo** [comment]
Also get this issue on `1.18.0-beta0`

**Comment by zorn-v** [comment]
https://github.com/olmokramer/atom-permanent-delete/pull/11

**Comment by natorojr** [comment]
Is this extension dead?

If not, please merge fix.

**Comment by jetsbee** [comment]
You can fix the code to use permanent-delete package.

1. Go to Settings in Atom.
2. In Packages menu, click Settings button for permanent-delete package box.
3. Click View Code button.
4. Open lib/permanent-delete.js
5. Change 26 line of code.
// treeView = treeView.mainModule.createView();
  treeView = treeView.mainModule.treeView;
6. Reload the atom editor.
7. Then use permanent-delete package.

**Comment by av-nexter** [comment]
Problem can be solved, in "~/.atom/packages/permanent-delete/lib/permanent-delete.js" file, replace line 26
treeView = treeView.mainModule.createView();
to
treeView = treeView.mainModule.getTreeViewInstance();
Now author seems to have abandoned project
