### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, unlink '/Users/tomi/Documents/Programming/Github/HugosAwesomeWorld/src/modules/schedules/client/schedule_subscription.ts'

### ISSUE THREAD

**Issue by tomitrescak** [olmokramer/atom-permanent-delete#3]
[Enter steps to reproduce below:]
1. Select multiple files
2. Click "Permanent Delete"

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [permanent-delete](https://github.com/olmokramer/atom-permanent-delete) package, v0.1.2
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, unlink '/Users/tomi/Documents/Programming/Github/HugosAwesomeWorld/src/modules/schedules/client/schedule_subscription.ts'

```
At fs.js:939

Error: ENOENT: no such file or directory, unlink '/Users/tomi/Documents/Programming/Github/HugosAwesomeWorld/src/modules/schedules/client/schedule_subscription.ts'
  at Error (native)
  at Object.fs.unlinkSync (fs.js:939:18)
  at /Users/tomi/.atom/packages/permanent-delete/lib/permanent-delete.coffee:48:19
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:110:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```
### Commands

```
     -2:58.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:56.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:56.4.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:50.6.0 core:cut (atom-text-editor.editor.is-focused)
     -0:47 core:backspace (atom-text-editor.editor.is-focused)
     -0:46.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:44.6.0 core:undo (atom-text-editor.editor.is-focused)
     -0:42.3.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:41.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:39.8.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:35.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:34.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:31.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:30 core:undo (atom-text-editor.editor.is-focused)
     -0:22.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:17.1.0 core:paste (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-monokai"
    ],
    "disabledPackages": [
      "better-handlebars",
      "preview-plus",
      "tree-view-git-status",
      "sublime-tabs",
      "tab-history",
      "atom-handlebars",
      "meteor-helper",
      "enhanced-tabs"
    ],
    "ignoredNames": [
      ".settings",
      ".idea",
      ".git",
      ".DS_Store",
      "node_modules",
      "js",
      ".tmp",
      "documentation",
      ".meteor",
      ".build*",
      ".npm"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
Handlebars, v1.1.2
atom-beautify, v0.28.5
atom-html-preview, v0.1.8
atom-jasmine, v0.5.0
atom-monokai, v0.8.0
atom-typescript, v4.5.13
build, v0.38.0
docblockr, v0.7.2
git-plus, v5.1.2
linter, v0.12.7
linter-tslint, v0.2.2
permanent-delete, v0.1.2
project-manager, v1.15.10
recent-files-fuzzy-finder, v0.1.3
tab-switcher, v1.0.0
zentabs, v0.8.4

# Dev
No dev packages
```

**Comment by olmokramer** [comment]
Hey, thanks for reporting the issue :-)
I'm very busy at the moment, but i think I have some free time in the weekend to look at this.

**Comment by olmokramer** [comment]
I just published a new version that should fix this. Please let me know if it works :)
