### ISSUE TITLE
Uncaught Error: ENOTEMPTY: directory not empty, rmdir 'H:\symfony\bin'

### ISSUE THREAD

**Issue by Deskit** [olmokramer/atom-permanent-delete#7]
[Enter steps to reproduce below:]
1. Shift + Supr
2. Delete Project Folder Path UNC

**Atom Version**: 1.7.2
**System**: Windows 10 Pro 64 Bit
**Thrown From**: [permanent-delete](https://github.com/olmokramer/atom-permanent-delete) package, v0.1.5
### Stack Trace

Uncaught Error: ENOTEMPTY: directory not empty, rmdir 'H:\symfony\bin'

```
At /C:/Users/clust/.atom/packages/permanent-delete/lib/permanent-delete.js:0

Error: ENOTEMPTY: directory not empty, rmdir 'H:\symfony\bin'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:806:18)
    at rmdir (C:/Users/clust/.atom/packages/permanent-delete/lib/permanent-delete.js:58:6)
    at C:/Users/clust/.atom/packages/permanent-delete/lib/permanent-delete.js:56:5
    at traverse (C:\Users\clust\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:377:17)
    at Object.fsPlus.traverseTreeSync (C:\Users\clust\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:386:14)
    at rmdir (C:/Users/clust/.atom/packages/permanent-delete/lib/permanent-delete.js:53:6)
    at C:/Users/clust/.atom/packages/permanent-delete/lib/permanent-delete.js:47:21
    at C:\Users\clust\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:110:18
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
     -6:31.2.0 permanent-delete:delete (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:38.3.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -0:27.3.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:04.0 permanent-delete:delete (span.name.icon.icon-file-directory)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-php",
      "close-tags",
      "linter-htmlhint",
      "linter-bootlint",
      "autoclose-html"
    ],
    "projectHome": "F:\\Proyectos Web"
  }
}
```
### Installed Packages

``` coffee
# User
atom-bootstrap4, v1.4.0
atomic-chrome, v0.3.0
color-picker, v2.1.1
emmet, v2.4.3
file-icons, v1.7.7
highlight-selected, v0.11.2
linter, v1.11.4
merge-conflicts, v1.4.2
minimap, v4.22.1
permanent-delete, v0.1.5
pigments, v0.26.0
Remote-FTP, v0.7.20

# Dev
No dev packages
```

**Comment by alexrsagen** [comment]
Can confirm this is a bug, also having the same issue deleting a node_modules folder on an SMB network share.
